//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseForRent
{
    using System;
    using System.Collections.Generic;
    
    public partial class House
    {
        public House()
        {
            this.Tenants = new HashSet<Tenant>();
        }
    
        public System.DateTime Id { get; set; }
        public string House1 { get; set; }
        public string Style { get; set; }
        public int Price { get; set; }
        public int Elec { get; set; }
        public int Water { get; set; }
        public int Wifi { get; set; }
        public int Other { get; set; }
        public int Total { get; set; }
    
        public virtual ICollection<Tenant> Tenants { get; set; }
    }
}
