//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseForRent
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class House_for_RentEntities3 : DbContext
    {
        public House_for_RentEntities3()
            : base("name=House_for_RentEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<House> Houses { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Tenant> Tenants { get; set; }
    }
}
