//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseForRent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenant
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public System.DateTime House_id { get; set; }
        public string Hoten { get; set; }
        public string Gioitinh { get; set; }
        public string Quequan { get; set; }
        public Nullable<System.DateTime> Ngaysinh { get; set; }
        public Nullable<int> SoCMND { get; set; }
        public string Phone { get; set; }
        public string Dicchi { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual House House { get; set; }
    }
}
